# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Forms\jakosc_prod.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(493, 418)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_3 = QtWidgets.QWidget(self.widget_4)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.ed_sciezka_dane = QtWidgets.QLineEdit(self.widget_3)
        self.ed_sciezka_dane.setObjectName("ed_sciezka_dane")
        self.horizontalLayout.addWidget(self.ed_sciezka_dane)
        self.btn_przegladaj = QtWidgets.QPushButton(self.widget_3)
        self.btn_przegladaj.setObjectName("btn_przegladaj")
        self.horizontalLayout.addWidget(self.btn_przegladaj)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.btn_importuj = QtWidgets.QPushButton(self.widget_4)
        self.btn_importuj.setObjectName("btn_importuj")
        self.verticalLayout_2.addWidget(self.btn_importuj)
        self.verticalLayout_3.addWidget(self.widget_4)
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.tab_dane = QtWidgets.QTableWidget(self.widget)
        self.tab_dane.setObjectName("tab_dane")
        self.tab_dane.setColumnCount(0)
        self.tab_dane.setRowCount(0)
        self.verticalLayout_3.addWidget(self.tab_dane)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Jakość produkcji"))
        self.label_2.setText(_translate("Form", "v1"))
        self.label_3.setText(_translate("Form", "Ścieżka do pliku"))
        self.btn_przegladaj.setText(_translate("Form", "Przeglądaj"))
        self.btn_importuj.setText(_translate("Form", "Importuj"))
