# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms\plik_pomoc_raportowanie_total_prod.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(556, 408)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(4, 4, 4, 4)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_prev = QtWidgets.QPushButton(self.widget)
        self.btn_prev.setMaximumSize(QtCore.QSize(24, 48))
        self.btn_prev.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/img/svg_icons/chevron-left.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_prev.setIcon(icon)
        self.btn_prev.setObjectName("btn_prev")
        self.horizontalLayout.addWidget(self.btn_prev)
        self.lab_image = QtWidgets.QLabel(self.widget)
        self.lab_image.setMaximumSize(QtCore.QSize(500, 400))
        self.lab_image.setText("")
        self.lab_image.setPixmap(QtGui.QPixmap(":/pomoc/img/pomoc/follow up 1.png"))
        self.lab_image.setScaledContents(True)
        self.lab_image.setObjectName("lab_image")
        self.horizontalLayout.addWidget(self.lab_image)
        self.btn_next = QtWidgets.QPushButton(self.widget)
        self.btn_next.setMaximumSize(QtCore.QSize(24, 48))
        self.btn_next.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/img/svg_icons/chevron-right.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_next.setIcon(icon1)
        self.btn_next.setObjectName("btn_next")
        self.horizontalLayout.addWidget(self.btn_next)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
import icon_rc
import pomoc_rc
