# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/ustawieniaMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(194, 360)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_lokalizacje = QtWidgets.QPushButton(self.widget_2)
        self.btn_lokalizacje.setObjectName("btn_lokalizacje")
        self.verticalLayout.addWidget(self.btn_lokalizacje)
        self.btn_wc = QtWidgets.QPushButton(self.widget_2)
        self.btn_wc.setObjectName("btn_wc")
        self.verticalLayout.addWidget(self.btn_wc)
        self.btn_linie = QtWidgets.QPushButton(self.widget_2)
        self.btn_linie.setObjectName("btn_linie")
        self.verticalLayout.addWidget(self.btn_linie)
        self.btn_linie_wc = QtWidgets.QPushButton(self.widget_2)
        self.btn_linie_wc.setObjectName("btn_linie_wc")
        self.verticalLayout.addWidget(self.btn_linie_wc)
        self.btn_liderzy = QtWidgets.QPushButton(self.widget_2)
        self.btn_liderzy.setObjectName("btn_liderzy")
        self.verticalLayout.addWidget(self.btn_liderzy)
        self.btn_instruktorzy = QtWidgets.QPushButton(self.widget_2)
        self.btn_instruktorzy.setObjectName("btn_instruktorzy")
        self.verticalLayout.addWidget(self.btn_instruktorzy)
        self.btn_progiProd = QtWidgets.QPushButton(self.widget_2)
        self.btn_progiProd.setObjectName("btn_progiProd")
        self.verticalLayout.addWidget(self.btn_progiProd)
        self.btn_kwoty = QtWidgets.QPushButton(self.widget_2)
        self.btn_kwoty.setObjectName("btn_kwoty")
        self.verticalLayout.addWidget(self.btn_kwoty)
        self.btn_progiJak = QtWidgets.QPushButton(self.widget_2)
        self.btn_progiJak.setObjectName("btn_progiJak")
        self.verticalLayout.addWidget(self.btn_progiJak)
        self.btn_dniPracujace = QtWidgets.QPushButton(self.widget_2)
        self.btn_dniPracujace.setObjectName("btn_dniPracujace")
        self.verticalLayout.addWidget(self.btn_dniPracujace)
        self.btn_pomoc = QtWidgets.QPushButton(self.widget_2)
        self.btn_pomoc.setObjectName("btn_pomoc")
        self.verticalLayout.addWidget(self.btn_pomoc)
        self.btn_transport_cz = QtWidgets.QPushButton(self.widget_2)
        self.btn_transport_cz.setObjectName("btn_transport_cz")
        self.verticalLayout.addWidget(self.btn_transport_cz)
        self.gridLayout.addWidget(self.widget_2, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_lokalizacje.setText(_translate("Form", "Lokalizacje"))
        self.btn_wc.setText(_translate("Form", "WC"))
        self.btn_linie.setText(_translate("Form", "Linie"))
        self.btn_linie_wc.setText(_translate("Form", "linie <=> WC"))
        self.btn_liderzy.setText(_translate("Form", "Liderzy"))
        self.btn_instruktorzy.setText(_translate("Form", "Lider <=> WC"))
        self.btn_progiProd.setText(_translate("Form", "Wytyczne - Produktywność"))
        self.btn_kwoty.setText(_translate("Form", "Kwoty Jakości"))
        self.btn_progiJak.setText(_translate("Form", "Wytyczne - Jakość"))
        self.btn_dniPracujace.setText(_translate("Form", "Dni wolne w roku"))
        self.btn_pomoc.setText(_translate("Form", "Wsparcie Prod."))
        self.btn_transport_cz.setText(_translate("Form", "Transport Cz"))
