# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Forms\ustawieniaMenu_mag.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(194, 128)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_lokalizacje = QtWidgets.QPushButton(self.widget)
        self.btn_lokalizacje.setObjectName("btn_lokalizacje")
        self.verticalLayout.addWidget(self.btn_lokalizacje)
        self.btn_grupy = QtWidgets.QPushButton(self.widget)
        self.btn_grupy.setObjectName("btn_grupy")
        self.verticalLayout.addWidget(self.btn_grupy)
        self.btn_pracownicy = QtWidgets.QPushButton(self.widget)
        self.btn_pracownicy.setObjectName("btn_pracownicy")
        self.verticalLayout.addWidget(self.btn_pracownicy)
        self.btn_wytyczne_mag = QtWidgets.QPushButton(self.widget)
        self.btn_wytyczne_mag.setObjectName("btn_wytyczne_mag")
        self.verticalLayout.addWidget(self.btn_wytyczne_mag)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_lokalizacje.setText(_translate("Form", "Lokalizacje"))
        self.btn_grupy.setText(_translate("Form", "Grupy"))
        self.btn_pracownicy.setText(_translate("Form", "Pracownicy"))
        self.btn_wytyczne_mag.setText(_translate("Form", "Wytyczne Magazynu"))
